# Generated by Django 3.0.4 on 2020-06-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('copyright', models.TextField(blank=True, default=None, null=True)),
                ('docs', models.TextField(blank=True, default=None, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('last_build_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('managing_editor', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('pub_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('web_master', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('generator', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('comments', models.URLField(blank=True, default=None, null=True)),
                ('pubDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_reader.Channel')),
            ],
        ),
    ]
